=== JRI11930/proyectoBD-XML/prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inmobiliaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agentes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="apellido" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id_agente" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="propiedades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propiedad" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion">
                                            <xs:complexType>
                                                <xs:attribute name="colonia" use="required" />
                                                <xs:attribute name="calle" use="required" />
                                                <xs:attribute name="numero" type="xs:integer"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="area" type="xs:string" />
                                        <xs:element name="tipo" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id_propiedad" type="xs:ID"
                                        use="required" />
                                    <xs:attribute name="id_agente" type="xs:IDREF" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contratos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="contrato" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="f_expedicion">
                                            <xs:complexType>
                                                <xs:attribute name="fecha" type="xs:date"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="cliente">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" />
                                                    <xs:element name="apellido" type="xs:string" />
                                                    <xs:element name="telefono" type="xs:string" />
                                                    <xs:element name="correo" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="id_cliente" type="xs:ID"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="propiedad">
                                            <xs:complexType>
                                                <xs:attribute name="id_propiedad" type="xs:IDREF"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id_contrato" type="xs:ID"
                                        use="required" />
                                    <xs:attribute name="id_agente" type="xs:IDREF" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JRI11930/proyectoBD-XML/prueba.xml
<inmobiliaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="prueba.xsd">
    <agentes>
        <agente id_agente="a01">
            <nombre>Hortencio</nombre>
            <apellido>López</apellido>
        </agente>
        <agente id_agente="a02">
            <nombre>María</nombre>
            <apellido>Bermudez</apellido>
        </agente>
    </agentes>

    <propiedades>
        <propiedad id_propiedad="p01" id_agente="a01">
            <direccion colonia="Col 1" calle="Av 1" numero="37" />
            <precio> 1000000</precio>
            <area>70</area>
            <tipo>local</tipo>
        </propiedad>
        <propiedad id_propiedad="p02" id_agente="a01">
            <direccion colonia="Col 1" calle="Av 1" numero="42" />
            <precio> 15000000</precio>
            <area>100</area>
            <tipo>casa</tipo>
        </propiedad>
        <propiedad id_propiedad="p03" id_agente="a02">
            <direccion colonia="Col 1" calle="Av 1" numero="64" />
            <precio> 2000000</precio>
            <area>80</area>
            <tipo>departamento</tipo>
        </propiedad>
    </propiedades>

    <contratos>
        <contrato id_contrato="C01" id_agente="a01">
            <f_expedicion fecha="2024-05-12" />
            <cliente id_cliente="c01">
                <nombre>Juan</nombre>
                <apellido>Perez</apellido>
                <telefono>123456789</telefono>
                <correo>juan@correo.com</correo>
            </cliente>
            <propiedad id_propiedad="p01" />
        </contrato>

        <contrato id_contrato="C02" id_agente="a02">
            <f_expedicion fecha="2023-05-12" />
            <cliente id_cliente="c02">
                <nombre>María</nombre>
                <apellido>Ramírez</apellido>
                <telefono>345656876</telefono>
                <correo>maria@correo.com</correo>
            </cliente>
            <propiedad id_propiedad="p02" />
        </contrato>

        <contrato id_contrato="C03" id_agente="a02">
            <f_expedicion fecha="2024-03-12" />
            <cliente id_cliente="c03">
                <nombre>Sebastián</nombre>
                <apellido>González</apellido>
                <telefono>453278655</telefono>
                <correo>sebastian@correo.com</correo>
            </cliente>
            <propiedad id_propiedad="p03" />
        </contrato>

    </contratos>

</inmobiliaria>
